apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hermes

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: hermes

images:
  - name: ghcr.io/spacefrontiers/hermes/hermes-server
    newTag: latest
