apiVersion: v1
kind: Service
metadata:
  name: hermes-server
  namespace: hermes
  labels:
    app.kubernetes.io/name: hermes-server
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hermes-server
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
